# Dockerfile.server
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY P2P.py .

CMD ["python", "P2P.py", "--user_id", "server", "--port", "5000"]
